<a href="https://colab.research.google.com/github/Asim347/Python_Tasks/blob/main/Netflix_Dataset_Cleaning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

On this dataset, we will perform different operations like deleting redundant values, Dropping duplicates, Remove Nan values and also some more transformation.

In [1]:
from google.colab import files
uploaded = files.upload()

Saving netflix1.csv to netflix1.csv

In [75]:
import pandas as pd
df = pd.read_csv('netflix1.csv')
df.head()

,show_id,type,title,director,country,date_added,release_year,rating,duration,listed_in
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,United States,9/25/2021,2020,PG-13,90 min,Documentaries
1,s3,TV Show,Ganglands,Julien Leclercq,France,9/24/2021,2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act..."
2,s6,TV Show,Midnight Mass,Mike Flanagan,United States,9/24/2021,2021,TV-MA,1 Season,"TV Dramas, TV Horror, TV Mysteries"
3,s14,Movie,Confessions of an Invisible Girl,Bruno Garotti,Brazil,9/22/2021,2021,TV-PG,91 min,"Children & Family Movies, Comedies"
4,s8,Movie,Sankofa,Haile Gerima,United States,9/24/2021,1993,TV-MA,125 min,"Dramas, Independent Movies, International Movies"

In [37]:
df.shape[0]

8790

In [38]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8790 entries, 0 to 8789
Data columns (total 10 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   show_id       8790 non-null   object
 1   type          8790 non-null   object
 2   title         8790 non-null   object
 3   director      8790 non-null   object
 4   country       8790 non-null   object
 5   date_added    8790 non-null   object
 6   release_year  8790 non-null   int64
 7   rating        8790 non-null   object
 8   duration      8790 non-null   object
 9   listed_in     8790 non-null   object
dtypes: int64(1), object(9)
memory usage: 686.8+ KB

In [39]:
df.isnull().sum()

show_id         0
type            0
title           0
director        0
country         0
date_added      0
release_year    0
rating          0
duration        0
listed_in       0
dtype: int64

In [40]:
df.columns

Index(['show_id', 'type', 'title', 'director', 'country', 'date_added',
       'release_year', 'rating', 'duration', 'listed_in'],
      dtype='object')

In [10]:
df = df.drop(columns= 'rating')

In [12]:
df.columns

Index(['show_id', 'type', 'title', 'director', 'country', 'date_added',
       'release_year', 'duration', 'listed_in'],
      dtype='object')

In [23]:
new_col_names = []
for i in df.columns:
  new_col_names.append(i.capitalize())

['Show_id',
 'Type',
 'Title',
 'Director',
 'Country',
 'Date_added',
 'Release_year',
 'Duration',
 'Listed_in']

In [26]:
df.columns = new_col_names
df.columns

Index(['Show_id', 'Type', 'Title', 'Director', 'Country', 'Date_added',
       'Release_year', 'Duration', 'Listed_in'],
      dtype='object')

In [27]:
df.duplicated().sum()

np.int64(0)

In [28]:
df.isna().sum()

Show_id            0
Type               0
Title           8790
Director           0
Country            0
Date_added         0
Release_year       0
Duration           0
Listed_in          0
dtype: int64

In [36]:
df

,show_id,type,title,director,country,date_added,release_year,rating,duration,listed_in
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,United States,9/25/2021,2020,PG-13,90 min,Documentaries
1,s3,TV Show,Ganglands,Julien Leclercq,France,9/24/2021,2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act..."
2,s6,TV Show,Midnight Mass,Mike Flanagan,United States,9/24/2021,2021,TV-MA,1 Season,"TV Dramas, TV Horror, TV Mysteries"
3,s14,Movie,Confessions of an Invisible Girl,Bruno Garotti,Brazil,9/22/2021,2021,TV-PG,91 min,"Children & Family Movies, Comedies"
4,s8,Movie,Sankofa,Haile Gerima,United States,9/24/2021,1993,TV-MA,125 min,"Dramas, Independent Movies, International Movies"
...,...,...,...,...,...,...,...,...,...,...
8785,s8797,TV Show,Yunus Emre,Not Given,Turkey,1/17/2017,2016,TV-PG,2 Seasons,"International TV Shows, TV Dramas"
8786,s8798,TV Show,Zak Storm,Not Given,United States,9/13/2018,2016,TV-Y7,3 Seasons,Kids' TV
8787,s8801,TV Show,Zindagi Gulzar Hai,Not Given,Pakistan,12/15/2016,2012,TV-PG,1 Season,"International TV Shows, Romantic TV Shows, TV ..."
8788,s8784,TV Show,Yoko,Not Given,Pakistan,6/23/2018,2016,TV-Y,1 Season,Kids' TV
8789,s8786,TV Show,YOM,Not Given,Pakistan,6/7/2018,2016,TV-Y7,1 Season,Kids' TV

In [42]:
df.columns

Index(['show_id', 'type', 'title', 'director', 'country', 'date_added',
       'release_year', 'rating', 'duration', 'listed_in'],
      dtype='object')

In [43]:
df['show_id'].unique()

array(['s1', 's3', 's6', ..., 's8801', 's8784', 's8786'], dtype=object)

In [45]:
df['show_id']= df['show_id'].apply(lambda x: x.split('s')[0])

In [46]:
df

,show_id,type,title,director,country,date_added,release_year,rating,duration,listed_in
0,,Movie,Dick Johnson Is Dead,Kirsten Johnson,United States,9/25/2021,2020,PG-13,90 min,Documentaries
1,,TV Show,Ganglands,Julien Leclercq,France,9/24/2021,2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act..."
2,,TV Show,Midnight Mass,Mike Flanagan,United States,9/24/2021,2021,TV-MA,1 Season,"TV Dramas, TV Horror, TV Mysteries"
3,,Movie,Confessions of an Invisible Girl,Bruno Garotti,Brazil,9/22/2021,2021,TV-PG,91 min,"Children & Family Movies, Comedies"
4,,Movie,Sankofa,Haile Gerima,United States,9/24/2021,1993,TV-MA,125 min,"Dramas, Independent Movies, International Movies"
...,...,...,...,...,...,...,...,...,...,...
8785,,TV Show,Yunus Emre,Not Given,Turkey,1/17/2017,2016,TV-PG,2 Seasons,"International TV Shows, TV Dramas"
8786,,TV Show,Zak Storm,Not Given,United States,9/13/2018,2016,TV-Y7,3 Seasons,Kids' TV
8787,,TV Show,Zindagi Gulzar Hai,Not Given,Pakistan,12/15/2016,2012,TV-PG,1 Season,"International TV Shows, Romantic TV Shows, TV ..."
8788,,TV Show,Yoko,Not Given,Pakistan,6/23/2018,2016,TV-Y,1 Season,Kids' TV
8789,,TV Show,YOM,Not Given,Pakistan,6/7/2018,2016,TV-Y7,1 Season,Kids' TV

In [48]:
type(df['show_id'][0])

str

In [52]:
df["show_id"] = df["show_id"].astype(int)

ValueError: invalid literal for int() with base 10: ''

In [53]:
df[df['show_id'] == '']

,show_id,type,title,director,country,date_added,release_year,rating,duration,listed_in
0,,Movie,Dick Johnson Is Dead,Kirsten Johnson,United States,9/25/2021,2020,PG-13,90 min,Documentaries
1,,TV Show,Ganglands,Julien Leclercq,France,9/24/2021,2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act..."
2,,TV Show,Midnight Mass,Mike Flanagan,United States,9/24/2021,2021,TV-MA,1 Season,"TV Dramas, TV Horror, TV Mysteries"
3,,Movie,Confessions of an Invisible Girl,Bruno Garotti,Brazil,9/22/2021,2021,TV-PG,91 min,"Children & Family Movies, Comedies"
4,,Movie,Sankofa,Haile Gerima,United States,9/24/2021,1993,TV-MA,125 min,"Dramas, Independent Movies, International Movies"
...,...,...,...,...,...,...,...,...,...,...
8785,,TV Show,Yunus Emre,Not Given,Turkey,1/17/2017,2016,TV-PG,2 Seasons,"International TV Shows, TV Dramas"
8786,,TV Show,Zak Storm,Not Given,United States,9/13/2018,2016,TV-Y7,3 Seasons,Kids' TV
8787,,TV Show,Zindagi Gulzar Hai,Not Given,Pakistan,12/15/2016,2012,TV-PG,1 Season,"International TV Shows, Romantic TV Shows, TV ..."
8788,,TV Show,Yoko,Not Given,Pakistan,6/23/2018,2016,TV-Y,1 Season,Kids' TV
8789,,TV Show,YOM,Not Given,Pakistan,6/7/2018,2016,TV-Y7,1 Season,Kids' TV

In [56]:
df['date_added'] = df['date_added'].apply(lambda x: x.replace('/' , '-'))

In [57]:
df

,show_id,type,title,director,country,date_added,release_year,rating,duration,listed_in
0,,Movie,Dick Johnson Is Dead,Kirsten Johnson,United States,9-25-2021,2020,PG-13,90 min,Documentaries
1,,TV Show,Ganglands,Julien Leclercq,France,9-24-2021,2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act..."
2,,TV Show,Midnight Mass,Mike Flanagan,United States,9-24-2021,2021,TV-MA,1 Season,"TV Dramas, TV Horror, TV Mysteries"
3,,Movie,Confessions of an Invisible Girl,Bruno Garotti,Brazil,9-22-2021,2021,TV-PG,91 min,"Children & Family Movies, Comedies"
4,,Movie,Sankofa,Haile Gerima,United States,9-24-2021,1993,TV-MA,125 min,"Dramas, Independent Movies, International Movies"
...,...,...,...,...,...,...,...,...,...,...
8785,,TV Show,Yunus Emre,Not Given,Turkey,1-17-2017,2016,TV-PG,2 Seasons,"International TV Shows, TV Dramas"
8786,,TV Show,Zak Storm,Not Given,United States,9-13-2018,2016,TV-Y7,3 Seasons,Kids' TV
8787,,TV Show,Zindagi Gulzar Hai,Not Given,Pakistan,12-15-2016,2012,TV-PG,1 Season,"International TV Shows, Romantic TV Shows, TV ..."
8788,,TV Show,Yoko,Not Given,Pakistan,6-23-2018,2016,TV-Y,1 Season,Kids' TV
8789,,TV Show,YOM,Not Given,Pakistan,6-7-2018,2016,TV-Y7,1 Season,Kids' TV

In [76]:
df['country'].value_counts()

country
United States     3240
India             1057
United Kingdom     638
Pakistan           421
Not Given          287
                  ...
Luxembourg           1
Senegal              1
Belarus              1
Puerto Rico          1
Cyprus               1
Name: count, Length: 86, dtype: int64

In [77]:
df[df['country'] == 'Turkey']

,show_id,type,title,director,country,date_added,release_year,rating,duration,listed_in
950,s907,Movie,Have You Ever Seen Fireflies? - Theatre Play,Yılmaz Erdoğan,Turkey,5/7/2021,1999,TV-MA,118 min,"Dramas, International Movies"
1002,s977,Movie,Among Family,Ozan Açıktan,Turkey,4/23/2021,2017,TV-14,127 min,"Comedies, International Movies"
1003,s978,Movie,Dedemin Fisi,Meltem Bozoflu,Turkey,4/23/2021,2016,TV-14,101 min,"Comedies, International Movies"
1004,s979,Movie,Deliha,Hakan Algül,Turkey,4/23/2021,2014,TV-MA,102 min,"Comedies, International Movies, Romantic Movies"
1005,s980,Movie,Düğün Dernek,"Selçuk Aydemir, Birkan Pusa",Turkey,4/23/2021,2013,TV-MA,102 min,"Comedies, International Movies"
...,...,...,...,...,...,...,...,...,...,...
8530,s7246,TV Show,Kurt Seyit & Sura,Not Given,Turkey,12/26/2016,2014,TV-14,1 Season,"International TV Shows, Romantic TV Shows, TV ..."
8557,s7386,TV Show,Mahmut & Meryem,Not Given,Turkey,12/26/2016,2013,TV-14,1 Season,"International TV Shows, Romantic TV Shows, TV ..."
8770,s8721,TV Show,What Happens to My Family,Not Given,Turkey,5/5/2017,2016,TV-14,1 Season,"International TV Shows, TV Comedies, TV Dramas"
8778,s8750,TV Show,Winter Sun,Not Given,Turkey,8/1/2017,2014,TV-MA,1 Season,"International TV Shows, TV Dramas, TV Thrillers"
8785,s8797,TV Show,Yunus Emre,Not Given,Turkey,1/17/2017,2016,TV-PG,2 Seasons,"International TV Shows, TV Dramas"